# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c268b11d96b1f4d623e2c139735a6b39ec536e1b095ccac8db0dbb5a7760ed419cec6980223875ace485a3eefc44a2bfc018a125cfb168a0b2cf30a2d9329a1

test:
  secret_key_base: 939a4275daa73a0099a5a1f1088097fd33356c65acccb7274f5e90eb5fbff992771eb27ff5d365216e6b5446784107258acc771e9965a1abd7051a06bfcfaeea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
